# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
# fastlane_version = '2.93.1'

xcode_select('/Applications/Xcode-9.3.app')

default_platform(:ios)
app_name = 'Ham'
ipa = app_name + '.ipa'
xcode_select "/Applications/Xcode-9.3.app"
platform :ios do

  update_project_team(path: 'Hammer.xcodeproj', teamid: 'N9TVD38558')

  # get_certificates           # invokes cert
  # get_provisioning_profile   # invokes sigh
  
  lane :friends do
    build_app(workspace: 'Hammer.xcworkspace', scheme: 'Hammer')
    
 
  end

  desc 'Push a new beta build to TestFlight'
  lane :beta do
    #sync_code_signing(type: "appstore")    # see code signing guide for more information
    # increment_build_number(
    #   build_number: latest_testflight_build_number + 1,
    #   xcodeproj: "Ham-Supplies.xcodeproj", scheme: 'Ham-Supplies'
    # )
    build_app(workspace: 'Hammer.xcworkspace', scheme: 'Hammer')
    upload_to_testflight
  end
end

lane :certificates do
  match(app_identifier: ['com.flyingdinos.Hammer'], readonly: true)
end

lane :test do

  scan(
      skip_build: false,
      clean: true,
      workspace: 'Hammer.xcworkspace',
      scheme: 'Hammer',
      devices: ['iPhone 6s'],
      output_types: 'junit',
      output_files: 'unit.xml',
  )
end
